# Generated by Django 4.0.6 on 2022-08-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='texto',
            field=models.CharField(default='', max_length=9000),
            preserve_default=False,
        ),
    ]
